{
  "hash": "ff713224f9818a94f5e4efa61bb917dc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Metodologia e Funções de Cálculo\"\n---\n\n# Introdução\n\nEste capítulo apresenta a metodologia do modelo econômico e as funções de cálculo utilizadas na simulação.\n\n**Estrutura do capítulo:**\n\n1. Conversão dos dados observados para o cenário baseline\n2. Cálculo da economia em saúde\n3. Simulação da evolução do programa\n4. Cálculo dos indicadores econômicos\n\n---\n\n# Preparação\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999, digits = 2, OutDec = \",\")\n\nformatar_numero <- function(x, decimais = 0) {\n  format(round(x, decimais), big.mark = \".\", decimal.mark = \",\", nsmall = decimais)\n}\n\nformatar_moeda <- function(x) {\n  paste0(\"R$ \", formatar_numero(x))\n}\n```\n:::\n\n\n---\n\n# Parte 1: Conversão para o Cenário Baseline\n\n## O Problema\n\nOs estudos originais observaram eventos em uma população **mista**: 33,6% dos pacientes eram atendidos por médicos de família e 66,4% por médicos generalistas.\n\nPara calcular a economia potencial, precisamos saber: **quantos eventos ocorreriam se 100% da população fosse atendida por generalistas?**\n\nEste é o **cenário baseline** (0% de cobertura por médicos de família).\n\n## A Solução Matemática\n\nSe chamarmos de:\n\n- $E_{obs}$ = eventos observados na população mista\n- $E_{base}$ = eventos no cenário baseline (0% médicos de família)\n- $p_{MFC}$ = proporção atendida por médicos de família (0,336)\n- $p_{gen}$ = proporção atendida por generalistas (0,664)\n- $RR$ = risco relativo (taxa em médicos de família ÷ taxa em generalistas)\n\nA relação entre eventos observados e baseline é:\n\n$$E_{obs} = E_{base} \\times (p_{MFC} \\times RR + p_{gen})$$\n\nResolvendo para $E_{base}$:\n\n$$E_{base} = \\frac{E_{obs}}{p_{MFC} \\times RR + p_{gen}}$$\n\n## Função de Conversão\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconverter_para_baseline <- function(valor_observado, \n                                     risco_relativo, \n                                     proporcao_mfc = 0.336, \n                                     proporcao_gen = 0.664,\n                                     populacao_estudo = 600000, \n                                     populacao_alvo = 500000) {\n  #' Converte eventos observados para o cenário baseline (0% médicos de família)\n  #'\n\n  #' @param valor_observado Número de eventos observados no estudo\n\n  #' @param risco_relativo Razão entre taxa de médicos de família e generalistas\n  #' @param proporcao_mfc Proporção de pacientes atendidos por médicos de família no estudo\n  #' @param proporcao_gen Proporção de pacientes atendidos por generalistas no estudo\n  #' @param populacao_estudo População do estudo original\n  #' @param populacao_alvo População do município simulado\n  #'\n  #' @return Número de eventos esperados no baseline para a população alvo\n  \n  # Calcular o denominador (fator de mistura)\n  denominador <- (proporcao_mfc * risco_relativo) + proporcao_gen\n  \n  # Converter para baseline na população do estudo\n  baseline_estudo <- valor_observado / denominador\n  \n  # Ajustar para a população alvo\n  baseline_alvo <- baseline_estudo * (populacao_alvo / populacao_estudo)\n  \n  return(baseline_alvo)\n}\n```\n:::\n\n\n## Exemplo: Hemograma\n\nVamos aplicar a função ao exame de hemograma:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dados do estudo\nhemograma_observado <- 51757  # eventos/ano na população mista\nhemograma_rr <- 0.53          # médicos de família solicitam 53% do que generalistas\n\n# Converter para baseline\nhemograma_baseline <- converter_para_baseline(\n  valor_observado = hemograma_observado,\n  risco_relativo = hemograma_rr\n)\n```\n:::\n\n\n| Cenário | Hemogramas/ano |\n|---------|----------------|\n| Observado (população mista) | 51.757 |\n| Baseline (0% médicos de família) | 51.219 |\n| Com 100% médicos de família | 27.146 |\n\n**Interpretação:** Se toda a população fosse atendida por generalistas, esperaríamos 51.219 hemogramas por ano. Com 100% de médicos de família, esse número cairia para 27.146.\n\n---\n\n# Parte 2: Cálculo da Economia em Saúde\n\n## Conceito\n\nA economia em saúde vem da **diferença** entre o que seria gasto com generalistas e o que é gasto com médicos de família:\n\n$$\\text{Economia} = E_{base} \\times (1 - RR) \\times \\text{Custo unitário}$$\n\nOnde:\n\n- $E_{base}$ = eventos no baseline\n- $(1 - RR)$ = redução proporcional de eventos\n- Custo unitário = valor do procedimento na tabela do Sistema Único de Saúde\n\n## Função Principal: Economia com 100% de Cobertura\n\nEsta função calcula a economia anual se **todas** as equipes fossem cobertas por médicos de família:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalcular_economia_total <- function(fator_correcao_internacoes = 1.5) {\n  #' Calcula a economia anual em saúde com 100% de cobertura por médicos de família\n  #'\n  #' @param fator_correcao_internacoes Fator para corrigir defasagem da tabela de internações\n  #'\n  #' @return Lista com economia por categoria e total\n  \n  custo_consulta <- 50.00\n  \n\n  # ==========================================\n  # ENCAMINHAMENTOS AMBULATORIAIS\n  # ==========================================\n  \n  enc_amb <- data.frame(\n    risco_relativo = c(0.40, 0.50, 0.45, 0.49, 0.54, 0.74, 0.57, 0.54,\n                       0.63, 0.42, 0.38, 0.35, 0.47, 1.17, 1.68, 1.09,\n                       0.71, 0.52, 0.86, 0.66),\n    observado = c(2008, 1835, 897, 4144, 903, 290, 1762, 480,\n                  603, 1021, 867, 1030, 830, 2390, 1173, 8713,\n                  2269, 4934, 738, 991)\n  )\n  \n  enc_amb$baseline <- mapply(converter_para_baseline, \n                              enc_amb$observado, \n                              enc_amb$risco_relativo)\n  enc_amb$economia <- enc_amb$baseline * (1 - enc_amb$risco_relativo) * custo_consulta\n  economia_enc_amb <- sum(enc_amb$economia)\n  \n  # ==========================================\n  # ENCAMINHAMENTOS CIRÚRGICOS\n  # ==========================================\n  \n  enc_cir <- data.frame(\n    risco_relativo = c(1.21, 0.87, 1.22, 0.91, 1.19, 0.87),\n    observado = c(4458, 989, 147, 1968, 859, 359)\n  )\n  \n  enc_cir$baseline <- mapply(converter_para_baseline, \n                              enc_cir$observado, \n                              enc_cir$risco_relativo)\n  enc_cir$economia <- enc_cir$baseline * (1 - enc_cir$risco_relativo) * custo_consulta\n  economia_enc_cir <- sum(enc_cir$economia)\n  \n  # ==========================================\n  # EXAMES DIAGNÓSTICOS\n  # ==========================================\n  \n  diag <- data.frame(\n    risco_relativo = c(0.66, 0.96, 0.76, 0.49, 0.72, 0.98),\n    observado = c(1201, 385, 510, 1090, 431, 2424),\n    custo = c(39.94, 13.20, 86.00, 48.16, 30.00, 45.00)\n  )\n  \n  diag$baseline <- mapply(converter_para_baseline, \n                           diag$observado, \n                           diag$risco_relativo)\n  diag$economia <- diag$baseline * (1 - diag$risco_relativo) * diag$custo\n  economia_diag <- sum(diag$economia)\n  \n  # ==========================================\n  # EXAMES LABORATORIAIS\n  # ==========================================\n  \n  lab <- data.frame(\n    risco_relativo = c(0.53, 0.85, 0.29, 0.42, 0.73, 0.46, 0.64, 0.81, \n                       0.94, 0.41, 0.82, 0.23, 0.71, 0.08, 0.13, 0.56, \n                       0.78, 0.48, 0.47, 0.69, 0.64, 0.74, 0.09, 0.67, \n                       0.44, 0.56, 0.60, 0.48, 0.47, 0.36),\n    observado = c(51757, 43746, 22577, 10517, 18265, 9072, 25720, 34673, \n                  31127, 22163, 33828, 15603, 11679, 791, 886, 5432, \n                  2304, 9181, 9363, 3505, 4386, 1957, 604, 41333, \n                  1866, 674, 863, 210, 216, 4365),\n    custo = c(4.11, 1.85, 1.85, 1.85, 1.85, 1.85, 7.86, 1.85, \n              3.51, 3.51, 3.51, 1.85, 8.96, 8.71, 8.71, 11.60, \n              2.01, 2.01, 2.01, 2.01, 3.51, 2.63, 1.65, 3.70, \n              1.85, 10.15, 10.15, 18.55, 18.55, 16.42)\n  )\n  \n  lab$baseline <- mapply(converter_para_baseline, \n                          lab$observado, \n                          lab$risco_relativo)\n  lab$economia <- lab$baseline * (1 - lab$risco_relativo) * lab$custo\n  economia_lab <- sum(lab$economia)\n  \n  # ==========================================\n  # INTERNAÇÕES EVITÁVEIS\n  # ==========================================\n  \n  internacoes <- data.frame(\n    risco_relativo = c(0.83, 0.76, 0.74, 0.62, 0.52, 0.79, 0.35, 0.78, \n                       0.45, 0.57, 0.36, 0.82, 1.06, 0.59),\n    observado = c(128, 160, 244, 271, 230, 86, 54, 136, \n                  45, 114, 116, 331, 28, 41),\n    custo = c(761.35, 1178.17, 1756.62, 4774.49, 2553.91, 957.47, \n              853.21, 646.69, 527.15, 1969.07, 1969.07, 679.82, \n              502.60, 612.67)\n  )\n  \n  internacoes$baseline <- mapply(converter_para_baseline, \n                                  internacoes$observado, \n                                  internacoes$risco_relativo)\n  internacoes$economia <- internacoes$baseline * \n                           (1 - internacoes$risco_relativo) * \n                           internacoes$custo * \n                           fator_correcao_internacoes\n  economia_internacoes <- sum(internacoes$economia)\n  \n  # ==========================================\n  # TOTALIZAÇÃO\n  # ==========================================\n  \n  economia_encaminhamentos <- economia_enc_amb + economia_enc_cir\n  economia_exames <- economia_diag + economia_lab\n  economia_total <- economia_encaminhamentos + economia_exames + economia_internacoes\n  \n  return(list(\n    encaminhamentos = economia_encaminhamentos,\n    exames = economia_exames,\n    internacoes = economia_internacoes,\n    total = economia_total\n  ))\n}\n```\n:::\n\n\n## Resultado: Economia Potencial\n\n\n::: {.cell}\n\n```{.r .cell-code}\neconomia <- calcular_economia_total(fator_correcao_internacoes = 1.5)\n```\n:::\n\n\n| Categoria | Economia Anual (100% cobertura) | Percentual |\n|-----------|--------------------------------|------------|\n| Encaminhamentos | R$ 504.331 | 16.6% |\n| Exames | R$ 615.020 | 20.2% |\n| Internações | R$ 1.919.752 | 63.2% |\n| **Total** | **R$ 3.039.103** | **100%** |\n\n**Interpretação:** Se todas as 100 equipes do município fossem cobertas por médicos de família, a economia anual seria de aproximadamente R$ 3.039.103.\n\n---\n\n# Parte 3: Economia do Modelo de Residência\n\n## Conceito\n\nO modelo de residência gera economia porque **1 preceptor supervisiona 2 equipes** com apoio de 4 residentes, enquanto o modelo tradicional precisaria de **2 médicos**.\n\n## Parâmetros de Custo\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncustos <- list(\n  # Médico\n  salario_base = 16000,\n  encargos_pct = 0.70,\n  \n\n  # Preceptor\n  adicional_preceptoria_pct = 0.10,\n  \n  # Residente\n  bolsa_mec = 4106.90,\n  complemento_ms = 4000.00,\n  \n  # Incentivo\n  incentivo_federal = 4500,\n  \n  # Operacional\n  custo_operacional_anual = 50000\n)\n\n# Cálculos derivados\ncustos$custo_medico <- custos$salario_base * (1 + custos$encargos_pct)\ncustos$adicional_preceptoria <- custos$salario_base * custos$adicional_preceptoria_pct\ncustos$custo_preceptor <- custos$custo_medico + \n                           custos$adicional_preceptoria * (1 + custos$encargos_pct)\ncustos$bolsa_total <- custos$bolsa_mec + custos$complemento_ms\n```\n:::\n\n\n## Comparativo: Modelo Tradicional versus Residência\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Para 2 equipes:\n\n# Modelo tradicional\ncusto_tradicional <- 2 * custos$custo_medico * 12\n\n# Modelo residência\ncusto_preceptor_anual <- custos$custo_preceptor * 12\ncusto_residentes_anual <- 4 * custos$bolsa_total * 12\nreceita_incentivo_anual <- 2 * custos$incentivo_federal * 12\ncusto_residencia <- custo_preceptor_anual + custo_residentes_anual - receita_incentivo_anual\n\n# Economia\neconomia_modelo <- custo_tradicional - custo_residencia\n```\n:::\n\n\n| Item | Modelo Tradicional | Modelo Residência |\n|------|-------------------|-------------------|\n| Médicos/Preceptor | 2 médicos | 1 preceptor |\n| Custo médicos/preceptor | R$ 652.800 | R$ 359.040 |\n| Residentes | - | 4 residentes |\n| Custo residentes | - | R$ 389.131 |\n| Incentivo federal | - | R$ -108.000 |\n| **Custo total anual** | **R$ 652.800** | **R$ 640.171** |\n\n**Economia por par de equipes-escola:** R$ 12.629 por ano\n\n---\n\n# Parte 4: Simulação do Programa\n\n## Função de Simulação\n\nEsta função simula a evolução do programa ao longo de 10 anos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimular_programa <- function(\n    taxa_retencao = 0.60,\n    adicional_especialidade_pct = 0.10,\n    fator_correcao_internacoes = 1.5,\n    taxa_desconto = 0.05,\n    horizonte = 10\n) {\n  #' Simula o programa de residência e calcula indicadores econômicos\n  #'\n  #' @param taxa_retencao Proporção dos formados que permanece no município\n  #' @param adicional_especialidade_pct Adicional salarial para médicos de família (sobre salário base)\n  #' @param fator_correcao_internacoes Fator de correção para custos de internação\n  #' @param taxa_desconto Taxa de desconto anual para valor presente\n  #' @param horizonte Número de anos da simulação\n  #'\n  #' @return Lista com indicadores e dados anuais\n  \n  # Parâmetros fixos\n  salario_base <- 16000\n  encargos_pct <- 0.70\n  bolsa_total <- 4106.90 + 4000.00\n  incentivo_federal <- 4500\n  custo_operacional <- 50000\n  n_equipes_total <- 100\n  \n  # Custos calculados\n  custo_medico <- salario_base * (1 + encargos_pct)\n  custo_preceptor <- custo_medico + salario_base * 0.10 * (1 + encargos_pct)\n  \n  # Vetores de evolução\n  anos <- 0:horizonte\n  n_anos <- length(anos)\n  \n  n_preceptores <- c(0, 4, rep(8, horizonte - 1))\n  n_equipes_escola <- c(0, 8, rep(16, horizonte - 1))\n  n_residentes <- c(0, 16, rep(32, horizonte - 1))\n  \n  # Formados retidos (acumulado)\n  formados_retidos <- numeric(n_anos)\n  for (i in 1:n_anos) {\n    if (i <= 3) {\n      formados_retidos[i] <- 0\n    } else if (i == 4) {\n      formados_retidos[i] <- round(16 * taxa_retencao)\n    } else {\n      formados_retidos[i] <- formados_retidos[i-1] + round(16 * taxa_retencao)\n    }\n  }\n  \n  # Cobertura por médicos de família\n  equipes_mfc <- pmin(n_equipes_escola + formados_retidos, n_equipes_total)\n  cobertura_mfc <- equipes_mfc / n_equipes_total\n  \n  # ==========================================\n  # ECONOMIA DO MODELO DE RESIDÊNCIA\n  # ==========================================\n  \n  custo_2medicos <- 2 * custo_medico * 12\n  custo_1prec_4res <- custo_preceptor * 12 + \n                       4 * bolsa_total * 12 - \n                       2 * incentivo_federal * 12\n  economia_por_par <- custo_2medicos - custo_1prec_4res\n  economia_modelo <- (n_equipes_escola / 2) * economia_por_par\n  \n  # ==========================================\n  # INVESTIMENTO EM FIXAÇÃO\n  # ==========================================\n  \n  adicional_mensal <- salario_base * adicional_especialidade_pct\n  investimento_fixacao <- formados_retidos * adicional_mensal * (1 + encargos_pct) * 12\n  \n  # ==========================================\n  # CUSTO OPERACIONAL\n  # ==========================================\n  \n  custo_operacional_vetor <- c(0, rep(custo_operacional, horizonte))\n  \n  # ==========================================\n  # ECONOMIA EM SAÚDE\n  # ==========================================\n  \n  economia_saude <- calcular_economia_total(fator_correcao_internacoes)\n  beneficio_saude <- economia_saude$total * cobertura_mfc\n  \n  # ==========================================\n  # SALDO E VALOR PRESENTE\n  # ==========================================\n  \n  economia_pessoal <- economia_modelo - investimento_fixacao - custo_operacional_vetor\n  saldo <- economia_pessoal + beneficio_saude\n  \n  fator_desconto <- 1 / ((1 + taxa_desconto) ^ anos)\n  saldo_valor_presente <- saldo * fator_desconto\n  valor_presente_liquido <- sum(saldo_valor_presente)\n  \n  # ==========================================\n  # RETORNO\n  # ==========================================\n  \n  dados <- data.frame(\n    ano = anos,\n    preceptores = n_preceptores,\n    equipes_escola = n_equipes_escola,\n    residentes = n_residentes,\n    formados_retidos = formados_retidos,\n    equipes_mfc = equipes_mfc,\n    cobertura_mfc = cobertura_mfc,\n    economia_modelo = economia_modelo,\n    investimento_fixacao = investimento_fixacao,\n    custo_operacional = custo_operacional_vetor,\n    economia_pessoal = economia_pessoal,\n    beneficio_saude = beneficio_saude,\n    saldo = saldo,\n    saldo_valor_presente = saldo_valor_presente\n  )\n  \n  return(list(\n    valor_presente_liquido = valor_presente_liquido,\n    cobertura_final = cobertura_mfc[n_anos],\n    formados_total = formados_retidos[n_anos],\n    economia_modelo_total = sum(economia_modelo),\n    investimento_fixacao_total = sum(investimento_fixacao),\n    beneficio_saude_total = sum(beneficio_saude),\n    dados = dados\n  ))\n}\n```\n:::\n\n\n## Exemplo: Cenário Base\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresultado <- simular_programa(\n  taxa_retencao = 0.60,\n  adicional_especialidade_pct = 0.10\n)\n```\n:::\n\n\n### Evolução do Programa\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevolucao <- resultado$dados[, c(\"ano\", \"preceptores\", \"equipes_escola\", \n                                 \"residentes\", \"formados_retidos\", \"equipes_mfc\")]\nevolucao$cobertura <- paste0(round(resultado$dados$cobertura_mfc * 100, 0), \"%\")\n\nknitr::kable(\n  evolucao,\n  col.names = c(\"Ano\", \"Preceptores\", \"Equipes-Escola\", \"Residentes\", \n                \"Formados Retidos\", \"Equipes com Médico de Família\", \"Cobertura\"),\n  caption = \"Evolução do programa ao longo de 10 anos\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Evolução do programa ao longo de 10 anos\n\n| Ano| Preceptores| Equipes-Escola| Residentes| Formados Retidos| Equipes com Médico de Família|Cobertura |\n|---:|-----------:|--------------:|----------:|----------------:|-----------------------------:|:---------|\n|   0|           0|              0|          0|                0|                             0|0%        |\n|   1|           4|              8|         16|                0|                             8|8%        |\n|   2|           8|             16|         32|                0|                            16|16%       |\n|   3|           8|             16|         32|               10|                            26|26%       |\n|   4|           8|             16|         32|               20|                            36|36%       |\n|   5|           8|             16|         32|               30|                            46|46%       |\n|   6|           8|             16|         32|               40|                            56|56%       |\n|   7|           8|             16|         32|               50|                            66|66%       |\n|   8|           8|             16|         32|               60|                            76|76%       |\n|   9|           8|             16|         32|               70|                            86|86%       |\n|  10|           8|             16|         32|               80|                            96|96%       |\n\n\n:::\n:::\n\n\n### Fluxo Financeiro\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfluxo <- data.frame(\n  ano = resultado$dados$ano,\n  economia_modelo = round(resultado$dados$economia_modelo / 1000, 0),\n  investimento = round(resultado$dados$investimento_fixacao / 1000, 0),\n  beneficio = round(resultado$dados$beneficio_saude / 1000, 0),\n  saldo = round(resultado$dados$saldo / 1000, 0)\n)\n\nknitr::kable(\n  fluxo,\n  col.names = c(\"Ano\", \"Economia do Modelo\", \"Investimento em Fixação\", \n                \"Economia em Saúde\", \"Saldo\"),\n  caption = \"Fluxo financeiro anual (R$ mil)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Fluxo financeiro anual (R$ mil)\n\n| Ano| Economia do Modelo| Investimento em Fixação| Economia em Saúde| Saldo|\n|---:|------------------:|-----------------------:|-----------------:|-----:|\n|   0|                  0|                       0|                 0|     0|\n|   1|                 51|                       0|               243|   244|\n|   2|                101|                       0|               486|   537|\n|   3|                101|                     326|               790|   515|\n|   4|                101|                     653|              1094|   492|\n|   5|                101|                     979|              1398|   470|\n|   6|                101|                    1306|              1702|   447|\n|   7|                101|                    1632|              2006|   425|\n|   8|                101|                    1958|              2310|   402|\n|   9|                101|                    2285|              2614|   380|\n|  10|                101|                    2611|              2918|   357|\n\n\n:::\n:::\n\n\n### Indicadores Finais\n\n| Indicador | Valor |\n|-----------|-------|\n| Cobertura por médicos de família (ano 10) | 96% |\n| Médicos formados e retidos | 80 |\n| Economia do modelo (10 anos) | R$ 959.789 |\n| Investimento em fixação (10 anos) | R$ 11.750.400 |\n| Economia em saúde (10 anos) | R$ 15.560.208 |\n| **Valor Presente Líquido** | **R$ 3.309.523** |\n\n---\n\n# Parte 5: Conceitos Econômicos\n\n## Taxa de Desconto\n\nA **taxa de desconto** reflete o fato de que dinheiro hoje vale mais do que dinheiro no futuro. O Ministério da Saúde recomenda usar **5% ao ano** para avaliações econômicas em saúde.\n\n**Fórmula do valor presente:**\n\n$$VP = \\frac{VF}{(1 + r)^n}$$\n\nOnde:\n\n- $VP$ = valor presente\n- $VF$ = valor futuro\n- $r$ = taxa de desconto (0,05)\n- $n$ = número de anos\n\n## Valor Presente Líquido\n\nO **Valor Presente Líquido** é a soma de todos os saldos anuais convertidos para valor presente:\n\n$$VPL = \\sum_{t=0}^{T} \\frac{Saldo_t}{(1 + r)^t}$$\n\n**Interpretação:**\n\n| Resultado | Significado |\n|-----------|-------------|\n| Valor Presente Líquido > 0 | Programa economicamente viável |\n| Valor Presente Líquido = 0 | Programa se paga exatamente |\n| Valor Presente Líquido < 0 | Programa tem custo líquido |\n\n## Demonstração do Desconto Temporal\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndemo <- data.frame(\n  ano = 0:10,\n  valor_nominal = 1000\n)\n\ndemo$fator <- 1 / ((1 + 0.05) ^ demo$ano)\ndemo$valor_presente <- demo$valor_nominal * demo$fator\n\nknitr::kable(\n  demo[, c(\"ano\", \"valor_nominal\", \"valor_presente\")],\n  col.names = c(\"Ano\", \"Valor Nominal (R$)\", \"Valor Presente (R$)\"),\n  digits = c(0, 0, 2),\n  caption = \"Efeito do desconto temporal sobre R$ 1.000 (taxa 5% ao ano)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Efeito do desconto temporal sobre R$ 1.000 (taxa 5% ao ano)\n\n| Ano| Valor Nominal (R$)| Valor Presente (R$)|\n|---:|------------------:|-------------------:|\n|   0|               1000|                1000|\n|   1|               1000|                 952|\n|   2|               1000|                 907|\n|   3|               1000|                 864|\n|   4|               1000|                 823|\n|   5|               1000|                 784|\n|   6|               1000|                 746|\n|   7|               1000|                 711|\n|   8|               1000|                 677|\n|   9|               1000|                 645|\n|  10|               1000|                 614|\n\n\n:::\n:::\n\n\n**Interpretação:** R$ 1.000 recebidos no ano 10 equivalem a R$ 613.91 em valores de hoje.\n\n---\n\n# Resumo\n\nEste capítulo apresentou:\n\n1. **Função de conversão para baseline:** Transforma dados observados em estimativas para o cenário sem médicos de família\n\n2. **Função de economia em saúde:** Calcula a economia potencial com encaminhamentos, exames e internações\n\n3. **Economia do modelo de residência:** Demonstra que 1 preceptor + 4 residentes custa menos que 2 médicos\n\n4. **Função de simulação:** Projeta a evolução do programa e calcula indicadores econômicos\n\n5. **Conceitos econômicos:** Taxa de desconto e valor presente líquido\n\n**Principais achados do cenário base:**\n\n- Taxa de retenção: 60%\n- Adicional por especialidade: 10%\n- Cobertura final: 96%\n- Valor Presente Líquido: R$ 3.309.523\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}